name: Bug Report
description: Report a bug in the application
title: "[BUG] "
labels: bug
assignees: []  # This is an empty array

body:
  - type: markdown
    attributes:
      value: |
        **Describe the Issue**
        Please explain what is wrong.

  - type: input
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: "Describe how to reproduce the issue."
      placeholder: "1. Go to...\n2. Click on...\n3. The error appears..."

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: "Describe what you expected to see."
      placeholder: "Describe the expected behavior"

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: "Please provide any additional information that may help in resolving the issue."
      placeholder: "Attach screenshots, error logs, and other information"
