name: Сообщение об ошибке
description: Используйте этот шаблон для сообщения об ошибках в приложении.
title: "[Ошибка] "
labels: bug
assignees: []  # Здесь можно указать пользователей для назначения

body:
  - type: markdown
    attributes:
      value: |
        **Описание проблемы**
        Пожалуйста, опишите, что именно не так.

  - type: input
    id: steps-to-reproduce
    attributes:
      label: Шаги для воспроизведения
      description: "Опишите, как воспроизвести проблему."
      placeholder: "1. Перейдите на...\n2. Нажмите на...\n3. Ошибка появляется..."

  - type: textarea
    id: expected-behavior
    attributes:
      label: Ожидаемое поведение
      description: "Опишите, что вы ожидали увидеть."
      placeholder: "Опишите ожидаемое поведение"

  - type: textarea
    id: additional-info
    attributes:
      label: Дополнительная информация
      description: "Прикрепите любые дополнительные данные, которые могут помочь в решении проблемы."
      placeholder: "Прикрепите скриншоты, журналы ошибок и другую информацию"
