name: Bug Report
description: Report a bug in the application
title: "[BUG] "
labels: bug
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        **Опишите проблему**
        Опишите, что именно не так.

  - type: input
    id: steps-to-reproduce
    attributes:
      label: Шаги для воспроизведения
      description: "Опишите, как воспроизвести проблему."
      placeholder: "1. Перейдите на...\n2. Нажмите на...\n3. Ошибка появляется..."

  - type: textarea
    id: expected-behavior
    attributes:
      label: Ожидаемое поведение
      description: "Опишите, что вы ожидали увидеть."
      placeholder: "Опишите ожидаемое поведение"

  - type: textarea
    id: additional-info
    attributes:
      label: Дополнительная информация
      description: "Прикрепите любые дополнительные данные, которые могут помочь в решении проблемы."
      placeholder: "Прикрепите скриншоты, журналы ошибок и другую информацию"
